# Generated by Django 3.1.4 on 2021-01-18 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bird',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latin_name', models.CharField(max_length=200)),
                ('french_name', models.CharField(max_length=200)),
                ('english_name', models.CharField(max_length=200)),
                ('summary', models.TextField()),
                ('source', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('url', models.URLField()),
                ('bird', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='main_app.bird')),
            ],
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture_file', models.ImageField(upload_to='')),
                ('source', models.URLField(blank=True)),
                ('bird', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pictures', to='main_app.bird')),
            ],
        ),
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sound_type', models.CharField(max_length=200)),
                ('audio_file', models.FileField(upload_to='')),
                ('source', models.URLField()),
                ('sonogram', models.ImageField(blank=True, upload_to='')),
                ('bird', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audios', to='main_app.bird')),
            ],
        ),
    ]
